# Generated by Django 4.2 on 2023-04-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('registeredAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.device')),
            ],
        ),
    ]
