# Generated by Django 4.2 on 2023-04-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePowerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='current',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='voltage',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='devicestatuslog',
            name='deviceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.device'),
        ),
        migrations.AddField(
            model_name='devicepowerlog',
            name='logId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.devicestatuslog'),
        ),
    ]
