# Generated by Django 4.2 on 2023-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_devicepowerlog_devicestatuslog_alter_device_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatuslog',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
