# Generated by Django 4.2 on 2023-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_alter_devicestatuslog_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatuslog',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
    ]
