# Generated by Django 4.2 on 2023-04-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_alter_devicestatuslog_endtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceStatusLog',
            new_name='DeviceTimerLog',
        ),
    ]
