# Generated by Django 4.2 on 2023-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_rename_devicestatuslog_devicetimerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='powerRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devicetimerlog',
            name='averagePower',
            field=models.FloatField(default=0),
        ),
    ]
