# Generated by Django 4.2 on 2023-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0007_device_powerrate_device_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceName',
            field=models.CharField(default='', max_length=12),
        ),
    ]
